image: node:latest

stages:
  - production

deploy_production:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=fierce-badlands-12125 --api-key=$HEROKU_API_KEY
  environment:
    name: production
  only:
    - master
